### PR TITLE
Freebsd support

### PR DESCRIPTION
**Pull request by mischief**
only lightly tested.

### CODE REVIEW

**Comment by mischief** [comment]
depends on https://github.com/go-freebsd/pf/pull/3

**Comment by zachfi** [comment]
Nice.  I get the following using this code.

```
❯ curl -s localhost:9107/metrics | grep ^pf_
pf_state_inserts_total 314444
pf_state_removals_total 314391
pf_state_searches_total 8.88443e+06
pf_state_total 0
```

**Comment by nick-owens-eero** [comment]
note that to get the other metrics you must set the loginterface in pf.conf. that's usually your egress.

**Comment by zachfi** [comment]
Ah, now I also get the following after setting loginterface.

```
pf_ipv4_bytes_in_total 2.16734536e+08
pf_ipv4_bytes_out_total 3.487393229e+09
pf_ipv4_packets_in_blocked_total 0
pf_ipv4_packets_in_passed_total 3.620137e+06
pf_ipv4_packets_out_blocked_total 320894
pf_ipv4_packets_out_passed_total 3.582972e+06
pf_ipv6_bytes_in_total 2.1242488051e+10
pf_ipv6_bytes_out_total 2.3899717635e+10
pf_ipv6_packets_in_blocked_total 12
pf_ipv6_packets_in_passed_total 4.9475827e+07
pf_ipv6_packets_out_blocked_total 153469
pf_ipv6_packets_out_passed_total 5.3549811e+07
```

**Comment by zalegrala** [comment]
Is there anything else needed here?  How can we help?

**Comment by nick-owens-eero** [comment]
> Is there anything else needed here? How can we help?

hi @zalegrala

first, the main branch is not maintained. i have not used this in a while myself on openbsd. IIRC there's some adjustments that need to be made for the ticketing system openbsd added for the pf ioctls...

second, i think i tested this on freebsd only once or twice. there's probably bugs, since i don't use freebsd either.

have you ran this code with this branch? did it work for you?

**Comment by zalegrala** [comment]
I currently only have FreeBSD, but I can test again if there is a chance this could make it to main.  I was reviewing old node-exporter issues for FreeBSD related topics, and this one popped up again.  Is there interest in getting this to `main` or is a fork more appropriate?

**Comment by mischief** [comment]
should be resolved by 56e05d22f10b541b2cfe26161367bdfd0e689494 and [mischief/gopf@97272bc4a0b66b5d5c4a4057a3e71d32f6be91b5](https://github.com/mischief/gopf/commit/97272bc4a0b66b5d5c4a4057a3e71d32f6be91b5). lightly tested today, i think queues should be covered for priq, cbq and hfsc for freebsd.

feel free to open another issue if you find a problem, but be prepared to wait a while again for an answer unless you want to write the code yourself :-)

**Comment by zalegrala** [comment]
I write go, so happy to submit PRs.  Good to know you're still around.  Thanks for the updates!

**Pull request closed without merging**
